### ISSUE TITLE
Plugin randomly broke after being fine

### ISSUE THREAD

**Issue by Nebzla** [filoghost/ChestCommands#117]
### What are you trying to do?
Use the plugin and 

### What have you tried so far?
Restarting, plugin already up to date, it worked fine before

### Platform

- Server version Paper 444
- Chest Commands version I cant check it because the whole plugin broke

### Additional context
An internal error occured when attempting to perform this command
19.02 14:07:12 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'cc' in plugin ChestCommands v3.1.4 - plugin is disabled.

This is the rror

**Comment by Nebzla** [comment]
19.02 14:13:26 [Server] INFO [ChestCommands] Enabling ChestCommands v3.1.4*
19.02 14:13:26 [Server] WARN [ChestCommands] Loaded class javassist.d from ViaBackwards v3.2.0 which is not a depend, softdepend or loadbefore of this plugin.
19.02 14:13:27 [Server] INFO [ChestCommands] PlaceholderAPI was found! External placeholders can be used.
19.02 14:13:27 [Server] ERROR Error occurred while enabling ChestCommands v3.1.4 (Is it up to date?)
19.02 14:13:27 [Server] INFO java.lang.ExceptionInInitializerError: null
19.02 14:13:27 [Server] INFO at com.gmail.filoghost.chestcommands.serializer.IconSerializer.loadIconFromSection(IconSerializer.java:49) ~[?:?]
19.02 14:13:27 [Server] INFO at com.gmail.filoghost.chestcommands.serializer.MenuSerializer.loadMenu(MenuSerializer.java:28) ~[?:?]
19.02 14:13:27 [Server] INFO at com.gmail.filoghost.chestcommands.ChestCommands.load(ChestCommands.java:213) ~[?:?]
19.02 14:13:27 [Server] INFO at com.gmail.filoghost.chestcommands.ChestCommands.onEnable(ChestCommands.java:131) ~[?:?]

Is my startup error i just updated paper to latest and still broken

**Comment by Nebzla** [comment]
Switched to a different GUI plugin due to terrible support.
