### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by PePPe6601** [filoghost/ChestCommands#164]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

[11:55:15 INFO]: [ChestCommands] Encountered 1 error(s) on load:

1) Error while initializing config file "menu\flash.yml": I/O exception while reading file.
--------[ Exception details ]--------
java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:352)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:178)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3399)
        at java.base/java.nio.file.Files.readAllLines(Files.java:3436)
        at ChestCommands.jar//me.filoghost.chestcommands.fcommons.config.ConfigLoader.load(ConfigLoader.java:53)
        at ChestCommands.jar//me.filoghost.chestcommands.config.ConfigManager.tryLoadMenus(ConfigManager.java:111)
        at ChestCommands.jar//me.filoghost.chestcommands.ChestCommands.load(ChestCommands.java:177)
        at ChestCommands.jar//me.filoghost.chestcommands.ChestCommands.onCheckedEnable(ChestCommands.java:124)
        at ChestCommands.jar//me.filoghost.chestcommands.fcommons.BaseJavaPlugin.onEnable(BaseJavaPlugin.java:21)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:319)
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
        at java.base/java.lang.Thread.run(Th
read.java:831)
-------------------------------------

### Chest Commands version

 ChestCommands version 4.0.3

### Additional information

[https://pastebin.com/ShsCcvRX](url)

**Comment by teleport2** [comment]
I have the same problem. It occurs when I use Russian characters in the config, do you also?

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
