### ISSUE TITLE
got this console error

### ISSUE THREAD

**Issue by GreenArrowlol** [filoghost/ChestCommands#168]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

I tried to open a panel but I got this error

[22:21:49 INFO]: GreenArrow99 issued server command: /cc open stats
[22:21:49 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'cc' in plugin ChestCommands v4.0.3
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
at me.filoghost.chestcommands.fcommons.command.multi.MethodReflectionSubCommand.execute(MethodReflectionSubCommand.java:99) ~[?:?]
at me.filoghost.chestcommands.fcommons.command.multi.MultiCommandManager.execute(MultiCommandManager.java:113) ~[?:?]
at me.filoghost.chestcommands.fcommons.command.CommandManager.onCommand(CommandManager.java:80) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
... 15 more
Caused by: java.lang.NullPointerException
at java.util.Calendar.setTime(Calendar.java:1770) ~[?:1.8.0_312]
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943) ~[?:1.8.0_312]
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936) ~[?:1.8.0_312]
at java.text.DateFormat.format(DateFormat.java:345) ~[?:1.8.0_312]
at com.andrei1058.bedwars.support.papi.PAPISupport.onPlaceholderRequest(PAPISupport.java:115) ~[?:?]
at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:31) ~[?:?]
at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:160) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[?:?]
at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[?:?]
at me.filoghost.chestcommands.hook.PlaceholderAPIHook.setPlaceholders(PlaceholderAPIHook.java:37) ~[?:?]
at me.filoghost.chestcommands.placeholder.PlaceholderManager.replaceDynamicPlaceholders(PlaceholderManager.java:57) ~[?:?]
at me.filoghost.chestcommands.placeholder.PlaceholderString.getValue(PlaceholderString.java:33) ~[?:?]
at me.filoghost.chestcommands.placeholder.PlaceholderStringList.lambda$getValue$0(PlaceholderStringList.java:47) ~[?:?]
at me.filoghost.chestcommands.fcommons.collection.CollectionUtils.transformImmutable(CollectionUtils.java:59) ~[?:?]
at me.filoghost.chestcommands.placeholder.PlaceholderStringList.getValue(PlaceholderStringList.java:47) ~[?:?]
at me.filoghost.chestcommands.icon.BaseConfigurableIcon.renderLore(BaseConfigurableIcon.java:262) ~[?:?]
at me.filoghost.chestcommands.icon.BaseConfigurableIcon.render(BaseConfigurableIcon.java:285) ~[?:?]
at me.filoghost.chestcommands.icon.InternalConfigurableIcon.render(InternalConfigurableIcon.java:100) ~[?:?]
at me.filoghost.chestcommands.icon.InternalConfigurableIcon.updateRendering(InternalConfigurableIcon.java:189) ~[?:?]
at me.filoghost.chestcommands.inventory.DefaultMenuView.refresh(DefaultMenuView.java:38) ~[?:?]
at me.filoghost.chestcommands.inventory.DefaultMenuView.<init>(DefaultMenuView.java:27) ~[?:?]
at me.filoghost.chestcommands.menu.BaseMenu.open(BaseMenu.java:48) ~[?:?]
at me.filoghost.chestcommands.menu.InternalMenu.open(InternalMenu.java:65) ~[?:?]
at me.filoghost.chestcommands.command.CommandHandler.open(CommandHandler.java:159) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
at me.filoghost.chestcommands.fcommons.command.multi.MethodReflectionSubCommand.execute(MethodReflectionSubCommand.java:94) ~[?:?]
at me.filoghost.chestcommands.fcommons.command.multi.MultiCommandManager.execute(MultiCommandManager.java:113) ~[?:?]
at me.filoghost.chestcommands.fcommons.command.CommandManager.onCommand(CommandManager.java:80) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"]
... 15 more

### Chest Commands version

4.0.3

### Additional information

the error only shows up for that panel and not anything else.

**Comment by filoghost** [comment]
Try updating to 4.0.4.
