### ISSUE TITLE
my gui isnt working

### ISSUE THREAD

**Issue by priyam1234-spec** [filoghost/ChestCommands#172]
### Confirmation

- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).
- [X] I have tested the [latest development build](https://ci.codemc.io/job/filoghost/job/ChestCommands) of Chest Commands and the bug is still present.
- [X] I have updated **Spigot** to the latest release for my particular Minecraft version.
- [X] I made sure the bug hasn't already been reported on the [issue tracker](https://github.com/filoghost/ChestCommands/issues?q=is%3Aissue).

### Description

i get a error when i made a bedwars stats menu it gets this error

### How to reproduce

i made a gui file like this 
######################
#+                  +#
#   MENU SETTINGS    #
#+                  +#
######################

menu-settings:
    name: 'Stats'
    rows: 6

    commands:
      - stats
    auto-refresh: 5.0
    open-actions:
    open-with-item:
        left-click: false
        right-click: true
        
######################
#+                  +#
#       ICONS        #
#+                  +#
######################

stats:
    MATERIAL: MAP
    POSITION-X: 5
    POSITION-Y: 3
    NAME: '&eStats'
    KEEP-OPEN: true
    LORE:
    - ''
    - 'Your Level: %bw1058_player_level%'
    - 'Progress: %bw1058_player_progress%'
    - ''
    - 'Games played: &6%bw1058_stats_gamesplayed%'
    - 'Beds was destroyed: &6%bw1058_stats_bedsdestroyed%'
    - ''
    - 'Final Kills: &a%bw1058_stats_finalkills%'
    - 'Final Deaths: &a%bw1058_stats_finaldeaths%'
    - ''
    - 'Kills: &a%bw1058_stats_kills%'
    - 'Wins: &a%bw1058_stats_wins%'
    - 'Losses: &a%bw1058_stats_losses%'
    - ''
    - 'First Played on: &a%bw1058_stats_firstplay%'

### Server version

Previous version : git-Paper-235 (MC: 1.18.2)

### Chest Commands version

ChestCommands version 4.0.3

### Additional information

[07:53:40 ERROR]: Could not pass event PlayerCommandPreprocessEvent to ChestCommands v4.0.3
java.lang.NullPointerException: date must not be null
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at java.util.Calendar.setTime(Calendar.java:1792) ~[?:?]
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:978) ~[?:?]
        at java.text.SimpleDateFormat.format(SimpleDateFormat.java:971) ~[?:?]
        at java.text.DateFormat.format(DateFormat.java:378) ~[?:?]
        at com.andrei1058.bedwars.support.papi.PAPISupport.onPlaceholderRequest(PAPISupport.java:115) ~[bedwars-plugin-22.3.4.jar:?]
        at me.clip.placeholderapi.PlaceholderHook.onRequest(PlaceholderHook.java:32) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.replacer.CharsReplacer.apply(CharsReplacer.java:161) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:70) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:98) ~[PlaceholderAPI-2.11.1.jar:?]
        at me.filoghost.chestcommands.hook.PlaceholderAPIHook.setPlaceholders(PlaceholderAPIHook.java:37) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.placeholder.PlaceholderManager.replaceDynamicPlaceholders(PlaceholderManager.java:57) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.placeholder.PlaceholderString.getValue(PlaceholderString.java:33) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.placeholder.PlaceholderStringList.lambda$getValue$0(PlaceholderStringList.java:47) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.fcommons.collection.CollectionUtils.transformImmutable(CollectionUtils.java:59) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.placeholder.PlaceholderStringList.getValue(PlaceholderStringList.java:47) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.icon.BaseConfigurableIcon.renderLore(BaseConfigurableIcon.java:262) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.icon.BaseConfigurableIcon.render(BaseConfigurableIcon.java:285) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.icon.InternalConfigurableIcon.render(InternalConfigurableIcon.java:100) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.icon.InternalConfigurableIcon.updateRendering(InternalConfigurableIcon.java:189) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.inventory.DefaultMenuView.refresh(DefaultMenuView.java:38) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.inventory.DefaultMenuView.<init>(DefaultMenuView.java:27) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.menu.BaseMenu.open(BaseMenu.java:48) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.menu.InternalMenu.open(InternalMenu.java:65) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.menu.InternalMenu.openCheckingPermission(InternalMenu.java:75) ~[ChestCommands.jar:?]
        at me.filoghost.chestcommands.listener.CommandListener.onCommand(CommandListener.java:31) ~[ChestCommands.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor279.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:git-Paper-216]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2281) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2100) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2081) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1423) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1400) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1393) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1371) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by filoghost** [comment]
I'm closing this issue as the plugin is now in maintenance-only mode and no support will be provided. Sorry for not answering, I failed to properly support the plugin due to lack of time.
