### ISSUE TITLE
My menu is a validated yml but there is an unknown error

### ISSUE THREAD

**Issue by CapichouK** [filoghost/ChestCommands#179]
### Confirmation

- [X] I have read the [documentation](https://filoghost.me/docs/chest-commands).
- [X] I have read the [FAQ](https://filoghost.me/docs/chest-commands/faq).

### Description

Hi ! I have just created a menu but when I do "/cc reload" there is this error in the console and I don't understand 
Anyone can help me please?

### Chest Commands version

4.0.3

### Additional information

1) Error while initializing config file "menu/menu.yml": I/O exception while reading file.
### --------[ Exception details ]--------
java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at java.nio.file.Files.readAllLines(Files.java:3205)
        at java.nio.file.Files.readAllLines(Files.java:3242)
        at me.filoghost.chestcommands.fcommons.config.ConfigLoader.load(ConfigLoader.java:53)
        at me.filoghost.chestcommands.config.ConfigManager.tryLoadMenus(ConfigManager.java:111)
        at me.filoghost.chestcommands.ChestCommands.load(ChestCommands.java:177)
        at me.filoghost.chestcommands.command.CommandHandler.reload(CommandHandler.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at me.filoghost.chestcommands.fcommons.command.multi.MethodReflectionSubCommand.execute(MethodReflectionSubCommand.java:94)
        at me.filoghost.chestcommands.fcommons.command.multi.MultiCommandManager.execute(MultiCommandManager.java:113)
        at me.filoghost.chestcommands.fcommons.command.CommandManager.onCommand(CommandManager.java:80)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1400)
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
        at java.lang.Thread.run(Thread.java:748)
-------------------------------------###

**Comment by CapichouK** [comment]
and there is my .yml :
https://pastebin.com/CvDXXkvx
