### ISSUE TITLE
Helpme Selling ChestCommands 1.14.4 server bug

### ISSUE THREAD

**Issue by fAnsixisreal** [filoghost/ChestCommands#29]
[ChestCommands] Task #256 for ChestCommands v3.2.0 generated an exception
java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.Material.getId(Material.java:3302) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at com.gmail.filoghost.chestcommands.internal.icon.ExtendedIcon.onClick(ExtendedIcon.java:185) ~[?:?]
        at com.gmail.filoghost.chestcommands.task.ExecuteCommandsTask.run(ExecuteCommandsTask.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by darksitegamers** [comment]
What version is your plugin?

**Comment by filoghost** [comment]
Please update the plugin, this bug was solved.
